### ISSUE TITLE
Incompatible type for element 2 in composite literal in main.go

### ISSUE THREAD

**Issue by advancedwebdeveloper** [pwaller/columnator#1]
Hi.

I am experiencing problems in compiling your project:

> ~/columnator$ go build
> # _/home/oceanfish81/columnator
> ./main.go:14:15: error: incompatible types in assignment
> ./main.go:27:9: error: incompatible type for element 1 in composite literal
> ./main.go:32:9: error: incompatible type for element 2 in composite literal

I am using

> $ go version
> go version go1.15.2 gollvm LLVM 12.0.0git linux/amd64

under Ubuntu 20.04.1 x86_64

> $ go env
> GO111MODULE=""
> GOARCH="amd64"
> GOBIN=""
> GOCACHE="/home/oceanfish81/.cache/go-build"
> GOENV="/home/oceanfish81/.config/go/env"
> GOEXE=""
> GOFLAGS=""
> GOHOSTARCH="amd64"
> GOHOSTOS="linux"
> GOINSECURE=""
> GOMODCACHE="/home/oceanfish81/go/pkg/mod"
> GONOPROXY=""
> GONOSUMDB=""
> GOOS="linux"
> GOPATH="/home/oceanfish81/go"
> GOPRIVATE=""
> GOPROXY="https://proxy.golang.org,direct"
> GOROOT="/home/oceanfish81/gollvm_dist"
> GOSUMDB="sum.golang.org"
> GOTMPDIR=""
> GOTOOLDIR="/home/oceanfish81/gollvm_dist/tools"
> GCCGO="/home/oceanfish81/gollvm_dist/bin/llvm-goc"
> AR="ar"
> CC="/usr/bin/clang"
> CXX="/usr/bin/clang++"
> CGO_ENABLED="1"
> GOMOD=""
> CGO_CFLAGS="-g -O2"
> CGO_CPPFLAGS=""
> CGO_CXXFLAGS="-g -O2"
> CGO_FFLAGS="-g -O2"
> CGO_LDFLAGS="-g -O2"
> PKG_CONFIG="pkg-config"
> GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build561677468=/tmp/go-build -gno-record-gcc-switches -funwind-tables"
>

**Comment by pwaller** [comment]
Hi, This was a personal project which didn't go anywhere, which is why it is undocumented. It looks as though some imported packages have changed in a backward-incompatible way since I wrote this, and it was before the introduction of go modules. If you really want it to work then you'd have to take versions of urfav/cli from the same era that this code was written. Please by all means report back if you get it working, but I'm not working on this any time soon, and I'm not sure what you're trying to gain by compiling this.
